updated sync_schema

diff --git a/sync_schema b/sync_schema
--- a/sync_schema
+++ b/sync_schema
@@ -2,6 +2,7 @@
 
 
 # Declare function to sync
+# copy schema xml
 copy()
 {
 	path="$1"
@@ -23,6 +24,44 @@ copy()
 	# printf '%s\n' treats variable as string and seperates via internal IFS=" "
 	# prints new line because $var is not in "$var", if it would be, the \n would happen after the $var
 	paste <(printf '%s\n' $origin) <(printf '%s\n' $dest) | xargs -n2 cp
+}
+
+copy_git()
+{
+	find -name "managed-schema.xml" \( -not -path "*/schema_files/*" -not -path "*/schema_backup/*" \) |\
+	head -n 1 |\
+	sed "s/\(.*\/server\/solr\).*/\1/"|\
+	xargs -I {} cp -r schema_files/* {}
+}
+
+git_pull()
+{
+	echo "▓Github » Pull Github schema▓"
+	echo "↓"
+	if ! git pull origin main; then
+		echo ""
+		echo "▓Github Error▓"
+		echo "↓"
+		echo "Git Pull failed. Consider to log in with your Github Account."
+		exit 1
+	fi
+	echo ""
+}
+
+git_push()
+{
+	echo "▓Github » Push local schema commit▓"
+	echo "↓"
+	git add schema_files/
+	git commit -m "updated schema $(date +"%D_%H-%M")"
+	if ! git push -u origin main; then
+		echo ""
+		echo "▓Github Error▓"
+		echo "↓"
+		echo "Git Push failed. Consider to log in with your Github Account."
+		exit 1
+	fi
+	echo ""
 }
 
 # Init Variables
@@ -85,21 +124,36 @@ do
 		esac
 done
 
+# ###################################################
+# # Safety Backup when conflicting command switches #
+# ###################################################
+# Backup when -togit -tolocal -syn are all chosen
+if [[ $togit -eq 1 && $tolocal -eq 1 ]]; then
+	read -p "
+	You chose full synching with -togit -tolocal. 
+	Do you want to backup your local schema?
+	!!Attention!!!
+	Your current backup will be replaced.
+	Answer with (y/n):" q_flag
+	if [[ $q_flag = "y" ]]; then
+		echo "▓Copying▓"
+		echo "↓"
+		echo "Start backing up schemas into schema_backup/"
+		copy schema_backup
+		echo ""
+	else
+		echo ""
+		echo "» No backup initiated."
+		echo ""
+	fi
+fi
+
 # ################################
 # # Local Schema to Goup Schema  #
 # ################################
 # Pull Github schema before pushing 
 if [[ $togit -eq 1 && $syn -eq 1 ]]; then
-	echo "▓Github » Pull Github schema▓"
-	echo "↓"
-	if ! git pull origin main; then
-		echo ""
-		echo "▓Github Error▓"
-		echo "↓"
-		echo "Git Pull failed. Consider to log in with your Github Account."
-		exit 1
-	fi
-	echo ""
+	git_pull
 fi
 
 # Copy local schema to group schema
@@ -114,18 +168,7 @@ fi
 
 # Create Commit & Push to Github
 if [[ $togit -eq 1 && $syn -eq 1 ]]; then
-	echo "▓Github » Push local schema commit▓"
-	echo "↓"
-	git add schema_files/
-	git commit -m "updated schema $(date +"%D_%H-%M")"
-	if ! git push -u origin main; then
-		echo ""
-		echo "▓Github Error▓"
-		echo "↓"
-		echo "Git Push failed. Consider to log in with your Github Account."
-		exit 1
-	fi
-	echo ""
+	git_push
 fi
 
 # ################################
@@ -134,16 +177,7 @@ fi
  
 # Pull Github schema
 if [[ $tolocal -eq 1 && $syn -eq 1 ]]; then
-	echo "▓Github » Pull Github schema▓"
-	echo "↓"
-	if ! git pull origin main; then
-		echo ""
-		echo "▓Github Error▓"
-		echo "↓"
-		echo "Git Pull failed. Consider to log in with your Github Account."
-		exit 1
-	fi
-	echo ""
+	git_pull
 fi
 
 # Copy group schema to own schema
@@ -152,10 +186,7 @@ if [[ $tolocal -eq 1 ]]; then
 	echo "▓Copying▓"
 	echo "↓"
 	echo "Start copying schemas to own schemas ..."
-	find -name "managed-schema.xml" \( -not -path "*/schema_files/*" -not -path "*/schema_backup/*" \) |\
-	head -n 1 |\
-	sed "s/\(.*\/server\/solr\).*/\1/"|\
-	xargs -I {} cp -r schema_files/* {}
+	copy_git
 	echo ""
 fi
 
