updated error handling in sync schema

diff --git a/sync_schema b/sync_schema
--- a/sync_schema
+++ b/sync_schema
@@ -4,15 +4,15 @@
 # Declare function to sync
 copy()
 {
-	path=$1
+	path="$1"
 	find -name "managed-schema.xml" \( -not -path "*/configsets/*" -not -path "*/schema_backup/*" -not -path "*/schema_files/*" \) |\
 	sed "s/.*\/server\/solr\/\(.*\)\/.*/\1/" | \
-	xargs -I {} mkdir -p $path"/"{} &&
+	xargs -I {} mkdir -p "$path/{}" &&
 
 	# Search all schema.xml paths and alter to new directory paths.
 	dest=$(find -name "managed-schema.xml" \( -not -path "*/configsets/*" -not -path "*/schema_backup/*" -not -path "*/schema_files/*" \) |\
 	sed "s/.*\/server\/solr\/\(.*\)/\1/" | \
-	xargs -I {} echo $path"/"{})  &&
+	xargs -I {} echo "$path/{}")  &&
 
 	# Search all original schema.xml paths and save paths
 	origin=$(find -name "managed-schema.xml" \( -not -path "*/configsets/*" -not -path "*/schema_backup/*" -not -path "*/schema_files/*" \) ) &&
@@ -92,7 +92,13 @@ done
 if [[ $togit -eq 1 && $syn -eq 1 ]]; then
 	echo "▓Github » Pull Github schema▓"
 	echo "↓"
-	git pull origin main
+	if ! git pull origin main; then
+		echo ""
+		echo "▓Github Error▓"
+		echo "↓"
+		echo "Git Pull failed. Consider to log in with your Github Account."
+		exit 1
+	fi
 	echo ""
 fi
 
@@ -112,7 +118,13 @@ if [[ $togit -eq 1 && $syn -eq 1 ]]; then
 	echo "↓"
 	git add schema_files/
 	git commit -m "updated schema $(date +"%D_%H-%M")"
-	git push -u origin main
+	if ! git push -u origin main; then
+		echo ""
+		echo "▓Github Error▓"
+		echo "↓"
+		echo "Git Push failed. Consider to log in with your Github Account."
+		exit 1
+	fi
 	echo ""
 fi
 
@@ -124,7 +136,13 @@ fi
 if [[ $tolocal -eq 1 && $syn -eq 1 ]]; then
 	echo "▓Github » Pull Github schema▓"
 	echo "↓"
-	git pull origin main
+	if ! git pull origin main; then
+		echo ""
+		echo "▓Github Error▓"
+		echo "↓"
+		echo "Git Pull failed. Consider to log in with your Github Account."
+		exit 1
+	fi
 	echo ""
 fi
 
@@ -156,4 +174,4 @@ fi
 
 echo "» Finished synchronizing schemas «"
 
-exit 1
+exit 0
